workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
